from django.shortcuts import render
from school.models import Student
from datetime import date, time
def home(request):
 student_data = Student.objects.all()
#  student_data = Student.objects.filter(name__exact="Sonam")
#  student_data = Student.objects.filter(name__iexact="Sonam")
#  student_data = Student.objects.filter(name__contains="S")
#  student_data = Student.objects.filter(name__icontains="i")
#  student_data = Student.objects.filter(id__in=[1, 3, 7])
#  student_data = Student.objects.filter(marks__gt=200)
#  student_data = Student.objects.filter(marks__gte=200)
#  student_data = Student.objects.filter(marks__lte=200)
#  student_data = Student.objects.filter(name__startswith='S')
#  student_data = Student.objects.filter(name__istartswith='S')
#  student_data = Student.objects.filter(name__endswith='t')
#  student_data = Student.objects.filter(name__iendswith='t')
#  student_data = Student.objects.filter(pass_date__range=('2024-01-01', '2024-12-24'))
#  student_data = Student.objects.filter(admission_date__date=date(2023, 8, 15))
#  student_data = Student.objects.filter(admission_date__date__gt=date(2022, 8, 15))
#  student_data = Student.objects.filter(pass_date__year=2023)
#  student_data = Student.objects.filter(pass_date__year__gt=2023)
#  student_data = Student.objects.filter(pass_date__month=12)
#  student_data = Student.objects.filter(pass_date__month_gt=5)
#  student_data = Student.objects.filter(pass_date__day=4)
#  student_data = Student.objects.filter(pass_date__day__gt=4)
#  student_data = Student.objects.filter(pass_date__week=15)
#  student_data = Student.objects.filter(pass_date__week__gt=15)
#  student_data = Student.objects.filter(pass_date__week_day=4)
#  student_data = Student.objects.filter(pass_date__week_day__gt=4)
#  student_data = Student.objects.filter(pass_date__quarter=1)
#  student_data = Student.objects.filter(pass_date__quarter__gt=2)
#  student_data = Student.objects.filter(admission_date__time=time(6,00))
#  student_data = Student.objects.filter(admission_date__time__gt=time(10,00))
#  student_data = Student.objects.filter(admission_date__hour=6)
#  student_data = Student.objects.filter(admission_date__hour__gt=5)
#  student_data = Student.objects.filter(admission_date__minute=40)
#  student_data = Student.objects.filter(admission_date__minute__gt=40)
#  student_data = Student.objects.filter(admission_date__second=40)
#  student_data = Student.objects.filter(admission_date__second__gt=40)
#  student_data = Student.objects.filter(roll__isnull=False)


 print("student_data:", student_data)
 return render(request, 'school/home.html', {'students':student_data})