# Generated by Django 6.0.2 on 2026-02-11 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_discountedproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='examcenter_ptr',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='DiscountedProduct',
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='ExamCenter',
        ),
    ]
