# Generated by Django 6.0.1 on 2026-01-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='CPR', max_length=70),
            preserve_default=False,
        ),
    ]
